config/routes.rb
Rails.application.routes.draw do

  root to:'static_pages#home'

  resources :events do

    collection do
      get "upcoming", to: 'events#upcoming'
    end

    member do
      get "planner", to: 'events#planner'
    end

    resources :comments, only: [:new, :create ]

  end

  namespace :admin do
    resources :events, only: [:index]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :event_mountain, :event_date, :event_leave_time, :location_point, :planner, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_event

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.event = @event
    @comment.save
    redirect_to event_path(@event)
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end


    def set_event
      @event = Event.find(params[:event_id])
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:planner ,:show, :edit, :update, :destroy]

  def planner
     @planner_name = @event.planner
  end

  def upcoming
    @upcoming_events = Event.where("event_date >= ?", Time.current)
  end

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    redirect_to events_path(@event)
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private

    def event_params
      params.require(:event).permit(:event_mountain, :event_date, :location_point, :event_leave_time, :planner, :description)
    end

    def set_event
      @event = Event.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/event_hikes_helper.rb
module EventHikesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Comments</h1>
      <%= simple_form_for [@event, @comment] do |f| %>
        <%= f.input :content,   label: 'Write your comment'%>
        <%= f.submit "Post Comment", class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <% if @event.errors.any? %>
    <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-inputs">
    <%= f.input :event_mountain, label:"Enter Moutain Name" %>
    <%= f.input :event_date, label:"Enter Date" %>
    <%= f.input :location_point, label: "Location Point" %>
    <%= f.input :event_leave_time, label: "Enter Leave Time" %>
    <%= f.input :planner,  label:"Planner name" %>
    <%= f.input :description, label: "Description" %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-success" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Edit Event</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Hello these are all planned Event Hikes</h1>
    </div>
  </div>
  <div class="row">
    <% @events.each do |event| %>
    <div class="col-xs-12 col-sm-4">
      <h2><%= event.event_mountain %></h2>
      <p>Hike On: <%= event.event_date.strftime('%a %d %b %Y')%></p>
      <p>Leaving At: <%= event.event_leave_time.strftime("%k:%M")%></p>
      <%= link_to "More Details", event_path(event), class:"btn btn-success" %>
      <%= link_to "Delete", event_path(event), method: :delete, class:"btn btn-danger", data: { confirm: "Are you sure?" } %>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-xs-12">
       <%= link_to "Add Event", new_event_path, class:"btn btn-success" %>
    </div>
  </div>

</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Create new event entry</h1>
      <%= render "form" %>
      </div>
  </div>
</div>

app/views/events/planner.html.erb
<h1>Planner of Hike:</h1>
<h2><%= @planner_name %></h2>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2><%= @event.event_mountain %></h2>
      <p>Hike On: <%= @event.event_date.strftime('%a %d %b %Y')%></p>
      <p>Leaving At: <%= @event.event_leave_time.strftime("%k:%M")%></p>
      <p>Location Point: <%= @event.location_point %></p>
      <p>Planner: <%= @event.planner %></p>
      <p>Description: <%= @event.description %><p/>
      <%= link_to "Edit", edit_event_path(@event), class:"btn btn-primary" %>
      <%= link_to "Back to all events", events_path, class:"btn btn-secondary" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h3>Comments</h3>
      <ul>
        <% @event.comments.each do |comment| %>
        <li><%= comment.content %></li>
        <% end %>
      </ul>
      <%= link_to "Add Comment", new_event_comment_path(@event), class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/events/upcoming.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>These are the upcoming hikes</h1>
    </div>
  </div>
  <div class="row">
    <% @upcoming_events.each do |event| %>
    <div class="col-xs-12 col-sm-4">
      <h2><%= event.event_mountain %></h2>
        <p>Hike On: <%= event.event_date.strftime('%a %d %b %Y')%></p>
        <p>Leaving At: <%= event.event_leave_time.strftime("%k:%M")%></p>
        <%= link_to "More Details", event_path(event), class:"btn btn-success" %>
      </div>
    <% end %>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hiking Buddies</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "partials/navbar" %>
    <%= yield %>
    <%= render "partials/footer" %>
  </body>
</html>

app/views/partials/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <span>HikingBuddies</span>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Trips</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<%= render "components/homebanner" %>
<div class="container">
<h2 class="text-center">Upcoming Hikes</h2>
  <%= render "components/homecards" %>
</div>